/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fPIC  -I/home/lee/.choosenim/toolchains/nim-0.18.0/lib -o /home/lee/python_codes/game_of_life/nim_lib/nimcache/cal_gene.o /home/lee/python_codes/game_of_life/nim_lib/nimcache/cal_gene.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NI tyArray_HU7qaqKu9czJLT84iCBJnsA[2];
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_LIB_EXPORT N_CDECL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, next_generation)(NI* cells, NI cellsLen_0, NI height, NI width);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgcal_gene)(NI* a, NI aLen_0, NI item);
static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAcal_gene)(NI* a, NI aLen_0, NI item);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, cal_geneDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_CONST tyArray_HU7qaqKu9czJLT84iCBJnsA TM_hh6scaMADSR4dCP6Zciy9bQ_42 = {((NI) 2),
((NI) 3)}
;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAcal_gene)(NI* a, NI aLen_0, NI item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_hh6scaMADSR4dCP6Zciy9bQ_40;
				NI TM_hh6scaMADSR4dCP6Zciy9bQ_41;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!(i == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_hh6scaMADSR4dCP6Zciy9bQ_40 = addInt(result, ((NI) 1));
				result = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_40);
				nimln_(2188, "system.nim");
				TM_hh6scaMADSR4dCP6Zciy9bQ_41 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_41);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgcal_gene)(NI* a, NI aLen_0, NI item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_b2asjP2y9cPDPwOLa1pD5PAcal_gene(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, next_generation)(NI* cells, NI cellsLen_0, NI height, NI width) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	NI cells_len;
	tyArray_nHXaesL0DJZHyVS07ARPRA T5_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T6_;
	nimfr_("next_generation", "cal_gene.nim");
	result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	nimln_(2, "cal_gene.nim");
	cells_len = cellsLen_0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				tyArray_nHXaesL0DJZHyVS07ARPRA T4_;
				NI TM_hh6scaMADSR4dCP6Zciy9bQ_2;
				if (!(i_2 < cellsLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(cellsLen_0)) raiseIndexError();
				i = cells[i_2];
				nimln_(4, "cal_gene.nim");
				memset((void*)T4_, 0, sizeof(T4_));
				T4_[0] = nimIntToStr(i);
				echoBinSafe(T4_, 1);
				nimln_(2188, "system.nim");
				TM_hh6scaMADSR4dCP6Zciy9bQ_2 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_2);
			} LA3: ;
		}
	}
	nimln_(5, "cal_gene.nim");
	memset((void*)T5_, 0, sizeof(T5_));
	T5_[0] = nimIntToStr(height);
	echoBinSafe(T5_, 1);
	nimln_(6, "cal_gene.nim");
	memset((void*)T6_, 0, sizeof(T6_));
	T6_[0] = nimIntToStr(width);
	echoBinSafe(T6_, 1);
	{
		NI i_3;
		NI i_4;
		i_3 = (NI)0;
		nimln_(3519, "system.nim");
		i_4 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_hh6scaMADSR4dCP6Zciy9bQ_48;
				if (!(i_4 < height)) goto LA9;
				nimln_(3521, "system.nim");
				i_3 = i_4;
				{
					NI j;
					NI i_5;
					j = (NI)0;
					nimln_(3519, "system.nim");
					i_5 = ((NI) 0);
					{
						nimln_(3520, "system.nim");
						while (1) {
							NI up;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_3;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_4;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_5;
							NI down;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_6;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_7;
							NI right;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_8;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_9;
							NI left;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_10;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_11;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_12;
							NI nw;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_13;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_14;
							NI n;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_15;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_16;
							NI ne;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_17;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_18;
							NI w;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_19;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_20;
							NI c;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_21;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_22;
							NI e;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_23;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_24;
							NI sw;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_25;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_26;
							NI s;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_27;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_28;
							NI se;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_29;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_30;
							NI neighbor_cell_sum;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_31;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_32;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_33;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_34;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_35;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_36;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_37;
							NI TM_hh6scaMADSR4dCP6Zciy9bQ_47;
							if (!(i_5 < width)) goto LA12;
							nimln_(3521, "system.nim");
							j = i_5;
							nimln_(11, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_3 = subInt(height, ((NI) 1));
							TM_hh6scaMADSR4dCP6Zciy9bQ_4 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_3), i_3);
							TM_hh6scaMADSR4dCP6Zciy9bQ_5 = modInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_4), height);
							up = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_5);
							nimln_(12, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_6 = addInt(i_3, ((NI) 1));
							TM_hh6scaMADSR4dCP6Zciy9bQ_7 = modInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_6), height);
							down = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_7);
							nimln_(13, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_8 = addInt(j, ((NI) 1));
							TM_hh6scaMADSR4dCP6Zciy9bQ_9 = modInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_8), width);
							right = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_9);
							nimln_(14, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_10 = subInt(width, ((NI) 1));
							TM_hh6scaMADSR4dCP6Zciy9bQ_11 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_10), j);
							TM_hh6scaMADSR4dCP6Zciy9bQ_12 = modInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_11), width);
							left = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_12);
							nimln_(16, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_13 = mulInt(up, height);
							TM_hh6scaMADSR4dCP6Zciy9bQ_14 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_13), left);
							if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_14)) >= (NU)(cellsLen_0)) raiseIndexError();
							nw = cells[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_14)];
							nimln_(17, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_15 = mulInt(up, height);
							TM_hh6scaMADSR4dCP6Zciy9bQ_16 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_15), j);
							if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_16)) >= (NU)(cellsLen_0)) raiseIndexError();
							n = cells[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_16)];
							nimln_(18, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_17 = mulInt(up, height);
							TM_hh6scaMADSR4dCP6Zciy9bQ_18 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_17), right);
							if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_18)) >= (NU)(cellsLen_0)) raiseIndexError();
							ne = cells[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_18)];
							nimln_(19, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_19 = mulInt(i_3, height);
							TM_hh6scaMADSR4dCP6Zciy9bQ_20 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_19), left);
							if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_20)) >= (NU)(cellsLen_0)) raiseIndexError();
							w = cells[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_20)];
							nimln_(20, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_21 = mulInt(i_3, height);
							TM_hh6scaMADSR4dCP6Zciy9bQ_22 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_21), j);
							if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_22)) >= (NU)(cellsLen_0)) raiseIndexError();
							c = cells[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_22)];
							nimln_(21, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_23 = mulInt(i_3, height);
							TM_hh6scaMADSR4dCP6Zciy9bQ_24 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_23), right);
							if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_24)) >= (NU)(cellsLen_0)) raiseIndexError();
							e = cells[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_24)];
							nimln_(22, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_25 = mulInt(down, height);
							TM_hh6scaMADSR4dCP6Zciy9bQ_26 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_25), left);
							if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_26)) >= (NU)(cellsLen_0)) raiseIndexError();
							sw = cells[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_26)];
							nimln_(23, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_27 = mulInt(down, height);
							TM_hh6scaMADSR4dCP6Zciy9bQ_28 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_27), j);
							if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_28)) >= (NU)(cellsLen_0)) raiseIndexError();
							s = cells[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_28)];
							nimln_(24, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_29 = mulInt(down, height);
							TM_hh6scaMADSR4dCP6Zciy9bQ_30 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_29), right);
							if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_30)) >= (NU)(cellsLen_0)) raiseIndexError();
							se = cells[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_30)];
							nimln_(25, "cal_gene.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_31 = addInt(nw, n);
							TM_hh6scaMADSR4dCP6Zciy9bQ_32 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_31), ne);
							TM_hh6scaMADSR4dCP6Zciy9bQ_33 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_32), w);
							TM_hh6scaMADSR4dCP6Zciy9bQ_34 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_33), e);
							TM_hh6scaMADSR4dCP6Zciy9bQ_35 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_34), sw);
							TM_hh6scaMADSR4dCP6Zciy9bQ_36 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_35), s);
							TM_hh6scaMADSR4dCP6Zciy9bQ_37 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_36), se);
							neighbor_cell_sum = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_37);
							nimln_(27, "cal_gene.nim");
							{
								NIM_BOOL T15_;
								NI TM_hh6scaMADSR4dCP6Zciy9bQ_38;
								NI TM_hh6scaMADSR4dCP6Zciy9bQ_39;
								T15_ = (NIM_BOOL)0;
								T15_ = (c == ((NI) 0));
								if (!(T15_)) goto LA16_;
								T15_ = (neighbor_cell_sum == ((NI) 3));
								LA16_: ;
								if (!T15_) goto LA17_;
								nimln_(28, "cal_gene.nim");
								TM_hh6scaMADSR4dCP6Zciy9bQ_38 = mulInt(i_3, height);
								TM_hh6scaMADSR4dCP6Zciy9bQ_39 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_38), j);
								if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_39)) >= (NU)(result->Sup.len)) raiseIndexError();
								result->data[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_39)] = ((NI) 1);
							}
							goto LA13_;
							LA17_: ;
							{
								NIM_BOOL T20_;
								NI TM_hh6scaMADSR4dCP6Zciy9bQ_43;
								NI TM_hh6scaMADSR4dCP6Zciy9bQ_44;
								nimln_(29, "cal_gene.nim");
								T20_ = (NIM_BOOL)0;
								T20_ = (c == ((NI) 1));
								if (!(T20_)) goto LA21_;
								T20_ = contains_P6sCVNQ9cdTFh3rtVXMEtxgcal_gene(TM_hh6scaMADSR4dCP6Zciy9bQ_42, 2, neighbor_cell_sum);
								LA21_: ;
								if (!T20_) goto LA22_;
								nimln_(30, "cal_gene.nim");
								TM_hh6scaMADSR4dCP6Zciy9bQ_43 = mulInt(i_3, height);
								TM_hh6scaMADSR4dCP6Zciy9bQ_44 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_43), j);
								if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_44)) >= (NU)(result->Sup.len)) raiseIndexError();
								result->data[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_44)] = ((NI) 1);
							}
							goto LA13_;
							LA22_: ;
							{
								NI TM_hh6scaMADSR4dCP6Zciy9bQ_45;
								NI TM_hh6scaMADSR4dCP6Zciy9bQ_46;
								nimln_(32, "cal_gene.nim");
								TM_hh6scaMADSR4dCP6Zciy9bQ_45 = mulInt(i_3, height);
								TM_hh6scaMADSR4dCP6Zciy9bQ_46 = addInt((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_45), j);
								if ((NU)((NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_46)) >= (NU)(result->Sup.len)) raiseIndexError();
								result->data[(NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_46)] = ((NI) 0);
							}
							LA13_: ;
							nimln_(3522, "system.nim");
							TM_hh6scaMADSR4dCP6Zciy9bQ_47 = addInt(i_5, ((NI) 1));
							i_5 = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_47);
						} LA12: ;
					}
				}
				TM_hh6scaMADSR4dCP6Zciy9bQ_48 = addInt(i_4, ((NI) 1));
				i_4 = (NI)(TM_hh6scaMADSR4dCP6Zciy9bQ_48);
			} LA9: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	cal_geneDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

void NIM_POSIX_INIT NimMainInit(void) {
	NimMain();
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("cal_gene", "cal_gene.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, cal_geneDatInit000)(void) {
}

